apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mynodeapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mynodeapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mynodeapp.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
